/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NhanVienRouteImport } from './routes/nhan-vien'
import { Route as LuyKeRouteImport } from './routes/luy-ke'
import { Route as DoanhThuRouteImport } from './routes/doanh-thu'
import { Route as IndexRouteImport } from './routes/index'

const NhanVienRoute = NhanVienRouteImport.update({
  id: '/nhan-vien',
  path: '/nhan-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const LuyKeRoute = LuyKeRouteImport.update({
  id: '/luy-ke',
  path: '/luy-ke',
  getParentRoute: () => rootRouteImport,
} as any)
const DoanhThuRoute = DoanhThuRouteImport.update({
  id: '/doanh-thu',
  path: '/doanh-thu',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doanh-thu': typeof DoanhThuRoute
  '/luy-ke': typeof LuyKeRoute
  '/nhan-vien': typeof NhanVienRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doanh-thu': typeof DoanhThuRoute
  '/luy-ke': typeof LuyKeRoute
  '/nhan-vien': typeof NhanVienRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doanh-thu': typeof DoanhThuRoute
  '/luy-ke': typeof LuyKeRoute
  '/nhan-vien': typeof NhanVienRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/doanh-thu' | '/luy-ke' | '/nhan-vien'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/doanh-thu' | '/luy-ke' | '/nhan-vien'
  id: '__root__' | '/' | '/doanh-thu' | '/luy-ke' | '/nhan-vien'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoanhThuRoute: typeof DoanhThuRoute
  LuyKeRoute: typeof LuyKeRoute
  NhanVienRoute: typeof NhanVienRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nhan-vien': {
      id: '/nhan-vien'
      path: '/nhan-vien'
      fullPath: '/nhan-vien'
      preLoaderRoute: typeof NhanVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luy-ke': {
      id: '/luy-ke'
      path: '/luy-ke'
      fullPath: '/luy-ke'
      preLoaderRoute: typeof LuyKeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doanh-thu': {
      id: '/doanh-thu'
      path: '/doanh-thu'
      fullPath: '/doanh-thu'
      preLoaderRoute: typeof DoanhThuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoanhThuRoute: DoanhThuRoute,
  LuyKeRoute: LuyKeRoute,
  NhanVienRoute: NhanVienRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
